<?php

namespace Modules\Geography\database\seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommuneSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('communes')->insert([
            ['name' => 'Arica', 'province_id' => 1],
            ['name' => 'Camarones', 'province_id' => 1],
            ['name' => 'Putre', 'province_id' => 2],
            ['name' => 'General Lagos', 'province_id' => 2],
            ['name' => 'Iquique', 'province_id' => 3],
            ['name' => 'Alto Hospicio', 'province_id' => 3],
            ['name' => 'Pozo Almonte', 'province_id' => 4],
            ['name' => 'Camiña', 'province_id' => 4],
            ['name' => 'Colchane', 'province_id' => 4],
            ['name' => 'Huara', 'province_id' => 4],
            ['name' => 'Pica', 'province_id' => 4],
            ['name' => 'Antofagasta', 'province_id' => 5],
            ['name' => 'Mejillones', 'province_id' => 5],
            ['name' => 'Sierra Gorda', 'province_id' => 5],
            ['name' => 'Taltal', 'province_id' => 5],
            ['name' => 'Calama', 'province_id' => 6],
            ['name' => 'Ollagüe', 'province_id' => 6],
            ['name' => 'San Pedro de Atacama', 'province_id' => 6],
            ['name' => 'Tocopilla', 'province_id' => 7],
            ['name' => 'María Elena', 'province_id' => 7],
            ['name' => 'Copiapó', 'province_id' => 8],
            ['name' => 'Caldera', 'province_id' => 8],
            ['name' => 'Tierra Amarilla', 'province_id' => 8],
            ['name' => 'Chañaral', 'province_id' => 9],
            ['name' => 'Diego de Almagro', 'province_id' => 9],
            ['name' => 'Vallenar', 'province_id' => 10],
            ['name' => 'Freirina', 'province_id' => 10],
            ['name' => 'Huasco', 'province_id' => 10],
            ['name' => 'Alto del Carmen', 'province_id' => 10],
            ['name' => 'La Serena', 'province_id' => 11],
            ['name' => 'Coquimbo', 'province_id' => 11],
            ['name' => 'Andacollo', 'province_id' => 11],
            ['name' => 'La Higuera', 'province_id' => 11],
            ['name' => 'Vicuña', 'province_id' => 11],
            ['name' => 'Paihuano', 'province_id' => 11],
            ['name' => 'Ovalle', 'province_id' => 12],
            ['name' => 'Combarbalá', 'province_id' => 12],
            ['name' => 'Monte Patria', 'province_id' => 12],
            ['name' => 'Punitaqui', 'province_id' => 12],
            ['name' => 'Río Hurtado', 'province_id' => 12],
            ['name' => 'Illapel', 'province_id' => 13],
            ['name' => 'Salamanca', 'province_id' => 13],
            ['name' => 'Los Vilos', 'province_id' => 13],
            ['name' => 'Canela', 'province_id' => 13],
            ['name' => 'Valparaíso', 'province_id' => 14],
            ['name' => 'Viña del Mar', 'province_id' => 14],
            ['name' => 'Concón', 'province_id' => 14],
            ['name' => 'Quintero', 'province_id' => 14],
            ['name' => 'Puchuncaví', 'province_id' => 14],
            ['name' => 'Casablanca', 'province_id' => 14],
            ['name' => 'Juan Fernández', 'province_id' => 14],
            ['name' => 'Quilpué', 'province_id' => 15],
            ['name' => 'Villa Alemana', 'province_id' => 15],
            ['name' => 'Limache', 'province_id' => 15],
            ['name' => 'Olmué', 'province_id' => 15],
            ['name' => 'San Antonio', 'province_id' => 16],
            ['name' => 'Cartagena', 'province_id' => 16],
            ['name' => 'El Tabo', 'province_id' => 16],
            ['name' => 'El Quisco', 'province_id' => 16],
            ['name' => 'Algarrobo', 'province_id' => 16],
            ['name' => 'Santo Domingo', 'province_id' => 16],
            ['name' => 'San Felipe', 'province_id' => 17],
            ['name' => 'Llaillay', 'province_id' => 17],
            ['name' => 'Catemu', 'province_id' => 17],
            ['name' => 'Panquehue', 'province_id' => 17],
            ['name' => 'Putaendo', 'province_id' => 17],
            ['name' => 'Santa María', 'province_id' => 17],
            ['name' => 'Los Andes', 'province_id' => 18],
            ['name' => 'Calle Larga', 'province_id' => 18],
            ['name' => 'Rinconada', 'province_id' => 18],
            ['name' => 'San Esteban', 'province_id' => 18],
            ['name' => 'La Ligua', 'province_id' => 19],
            ['name' => 'Cabildo', 'province_id' => 19],
            ['name' => 'Zapallar', 'province_id' => 19],
            ['name' => 'Papudo', 'province_id' => 19],
            ['name' => 'Petorca', 'province_id' => 19],
            ['name' => 'Quillota', 'province_id' => 20],
            ['name' => 'La Calera', 'province_id' => 20],
            ['name' => 'La Cruz', 'province_id' => 20],
            ['name' => 'Nogales', 'province_id' => 20],
            ['name' => 'Hijuelas', 'province_id' => 20],
            ['name' => 'Rapa Nui', 'province_id' => 21],
            ['name' => 'Santiago', 'province_id' => 22],
            ['name' => 'Cerrillos', 'province_id' => 22],
            ['name' => 'Cerro Navia', 'province_id' => 22],
            ['name' => 'Conchalí', 'province_id' => 22],
            ['name' => 'El Bosque', 'province_id' => 22],
            ['name' => 'Estación Central', 'province_id' => 22],
            ['name' => 'Huechuraba', 'province_id' => 22],
            ['name' => 'Independencia', 'province_id' => 22],
            ['name' => 'La Cisterna', 'province_id' => 22],
            ['name' => 'La Florida', 'province_id' => 22],
            ['name' => 'La Granja', 'province_id' => 22],
            ['name' => 'La Pintana', 'province_id' => 22],
            ['name' => 'La Reina', 'province_id' => 22],
            ['name' => 'Las Condes', 'province_id' => 22],
            ['name' => 'Lo Barnechea', 'province_id' => 22],
            ['name' => 'Lo Espejo', 'province_id' => 22],
            ['name' => 'Lo Prado', 'province_id' => 22],
            ['name' => 'Macul', 'province_id' => 22],
            ['name' => 'Maipú', 'province_id' => 22],
            ['name' => 'Ñuñoa', 'province_id' => 22],
            ['name' => 'Pedro Aguirre Cerda', 'province_id' => 22],
            ['name' => 'Peñalolén', 'province_id' => 22],
            ['name' => 'Providencia', 'province_id' => 22],
            ['name' => 'Pudahuel', 'province_id' => 22],
            ['name' => 'Quilicura', 'province_id' => 22],
            ['name' => 'Quinta Normal', 'province_id' => 22],
            ['name' => 'Recoleta', 'province_id' => 22],
            ['name' => 'Renca', 'province_id' => 22],
            ['name' => 'San Joaquín', 'province_id' => 22],
            ['name' => 'San Miguel', 'province_id' => 22],
            ['name' => 'San Ramón', 'province_id' => 22],
            ['name' => 'Vitacura', 'province_id' => 22],
            ['name' => 'Colina', 'province_id' => 23],
            ['name' => 'Lampa', 'province_id' => 23],
            ['name' => 'Tiltil', 'province_id' => 23],
            ['name' => 'Puente Alto', 'province_id' => 24],
            ['name' => 'Pirque', 'province_id' => 24],
            ['name' => 'San José de Maipo', 'province_id' => 24],
            ['name' => 'San Bernardo', 'province_id' => 25],
            ['name' => 'Buin', 'province_id' => 25],
            ['name' => 'Paine', 'province_id' => 25],
            ['name' => 'Calera de Tango', 'province_id' => 25],
            ['name' => 'Melipilla', 'province_id' => 26],
            ['name' => 'Alhué', 'province_id' => 26],
            ['name' => 'Curacaví', 'province_id' => 26],
            ['name' => 'María Pinto', 'province_id' => 26],
            ['name' => 'San Pedro', 'province_id' => 26],
            ['name' => 'Talagante', 'province_id' => 27],
            ['name' => 'El Monte', 'province_id' => 27],
            ['name' => 'Isla de Maipo', 'province_id' => 27],
            ['name' => 'Padre Hurtado', 'province_id' => 27],
            ['name' => 'Peñaflor', 'province_id' => 27],
            ['name' => 'Rancagua', 'province_id' => 28],
            ['name' => 'Codegua', 'province_id' => 28],
            ['name' => 'Coinco', 'province_id' => 28],
            ['name' => 'Coltauco', 'province_id' => 28],
            ['name' => 'Doñihue', 'province_id' => 28],
            ['name' => 'Graneros', 'province_id' => 28],
            ['name' => 'Las Cabras', 'province_id' => 28],
            ['name' => 'Machalí', 'province_id' => 28],
            ['name' => 'Malloa', 'province_id' => 28],
            ['name' => 'Mostazal', 'province_id' => 28],
            ['name' => 'Olivar', 'province_id' => 28],
            ['name' => 'Peumo', 'province_id' => 28],
            ['name' => 'Pichidegua', 'province_id' => 28],
            ['name' => 'Quinta de Tilcoco', 'province_id' => 28],
            ['name' => 'Rengo', 'province_id' => 28],
            ['name' => 'Requínoa', 'province_id' => 28],
            ['name' => 'San Vicente', 'province_id' => 28],
            ['name' => 'San Fernando', 'province_id' => 29],
            ['name' => 'Chépica', 'province_id' => 29],
            ['name' => 'Chimbarongo', 'province_id' => 29],
            ['name' => 'Lolol', 'province_id' => 29],
            ['name' => 'Nancagua', 'province_id' => 29],
            ['name' => 'Palmilla', 'province_id' => 29],
            ['name' => 'Peralillo', 'province_id' => 29],
            ['name' => 'Placilla', 'province_id' => 29],
            ['name' => 'Pumanque', 'province_id' => 29],
            ['name' => 'Santa Cruz', 'province_id' => 29],
            ['name' => 'Pichilemu', 'province_id' => 30],
            ['name' => 'La Estrella', 'province_id' => 30],
            ['name' => 'Litueche', 'province_id' => 30],
            ['name' => 'Marchigüe', 'province_id' => 30],
            ['name' => 'Navidad', 'province_id' => 30],
            ['name' => 'Paredones', 'province_id' => 30],
            ['name' => 'Talca', 'province_id' => 31],
            ['name' => 'San Clemente', 'province_id' => 31],
            ['name' => 'Pelarco', 'province_id' => 31],
            ['name' => 'Pencahue', 'province_id' => 31],
            ['name' => 'Maule', 'province_id' => 31],
            ['name' => 'San Rafael', 'province_id' => 31],
            ['name' => 'Curepto', 'province_id' => 31],
            ['name' => 'Constitución', 'province_id' => 31],
            ['name' => 'Empedrado', 'province_id' => 31],
            ['name' => 'Río Claro', 'province_id' => 31],
            ['name' => 'Curicó', 'province_id' => 32],
            ['name' => 'Hualañé', 'province_id' => 32],
            ['name' => 'Licantén', 'province_id' => 32],
            ['name' => 'Molina', 'province_id' => 32],
            ['name' => 'Rauco', 'province_id' => 32],
            ['name' => 'Romeral', 'province_id' => 32],
            ['name' => 'Sagrada Familia', 'province_id' => 32],
            ['name' => 'Teno', 'province_id' => 32],
            ['name' => 'Vichuquén', 'province_id' => 32],
            ['name' => 'Linares', 'province_id' => 33],
            ['name' => 'Colbún', 'province_id' => 33],
            ['name' => 'Longaví', 'province_id' => 33],
            ['name' => 'Parral', 'province_id' => 33],
            ['name' => 'Retiro', 'province_id' => 33],
            ['name' => 'San Javier', 'province_id' => 33],
            ['name' => 'Villa Alegre', 'province_id' => 33],
            ['name' => 'Yerbas Buenas', 'province_id' => 33],
            ['name' => 'Cauquenes', 'province_id' => 34],
            ['name' => 'Chanco', 'province_id' => 34],
            ['name' => 'Pelluhue', 'province_id' => 34],
            ['name' => 'Chillán', 'province_id' => 35],
            ['name' => 'Chillán Viejo', 'province_id' => 35],
            ['name' => 'El Carmen', 'province_id' => 35],
            ['name' => 'Pemuco', 'province_id' => 35],
            ['name' => 'Pinto', 'province_id' => 35],
            ['name' => 'Quillón', 'province_id' => 35],
            ['name' => 'San Ignacio', 'province_id' => 35],
            ['name' => 'Yungay', 'province_id' => 35],
            ['name' => 'Cobquecura', 'province_id' => 36],
            ['name' => 'Coelemu', 'province_id' => 36],
            ['name' => 'Ninhue', 'province_id' => 36],
            ['name' => 'Portezuelo', 'province_id' => 36],
            ['name' => 'Quirihue', 'province_id' => 36],
            ['name' => 'Ránquil', 'province_id' => 36],
            ['name' => 'Trehuaco', 'province_id' => 36],
            ['name' => 'Bulnes', 'province_id' => 37],
            ['name' => 'Coihueco', 'province_id' => 37],
            ['name' => 'Ñiquén', 'province_id' => 37],
            ['name' => 'San Carlos', 'province_id' => 37],
            ['name' => 'San Fabián', 'province_id' => 37],
            ['name' => 'San Nicolás', 'province_id' => 37],
            ['name' => 'Concepción', 'province_id' => 38],
            ['name' => 'Coronel', 'province_id' => 38],
            ['name' => 'Chiguayante', 'province_id' => 38],
            ['name' => 'Florida', 'province_id' => 38],
            ['name' => 'Hualpén', 'province_id' => 38],
            ['name' => 'Hualqui', 'province_id' => 38],
            ['name' => 'Lota', 'province_id' => 38],
            ['name' => 'Penco', 'province_id' => 38],
            ['name' => 'San Pedro de la Paz', 'province_id' => 38],
            ['name' => 'Santa Juana', 'province_id' => 38],
            ['name' => 'Talcahuano', 'province_id' => 38],
            ['name' => 'Tomé', 'province_id' => 38],
            ['name' => 'Arauco', 'province_id' => 39],
            ['name' => 'Cañete', 'province_id' => 39],
            ['name' => 'Contulmo', 'province_id' => 39],
            ['name' => 'Curanilahue', 'province_id' => 39],
            ['name' => 'Lebu', 'province_id' => 39],
            ['name' => 'Los Álamos', 'province_id' => 39],
            ['name' => 'Tirúa', 'province_id' => 39],
            ['name' => 'Los Ángeles', 'province_id' => 40],
            ['name' => 'Alto Biobío',  'province_id' => 40],
            ['name' => 'Antuco', 'province_id' => 40],
            ['name' => 'Cabrero', 'province_id' => 40],
            ['name' => 'Laja', 'province_id' => 40],
            ['name' => 'Mulchén', 'province_id' => 40],
            ['name' => 'Nacimiento', 'province_id' => 40],
            ['name' => 'Negrete', 'province_id' => 40],
            ['name' => 'Quilaco', 'province_id' => 40],
            ['name' => 'Quilleco', 'province_id' => 40],
            ['name' => 'San Rosendo', 'province_id' => 40],
            ['name' => 'Santa Bárbara', 'province_id' => 40],
            ['name' => 'Tucapel', 'province_id' => 40],
            ['name' => 'Yumbel', 'province_id' => 40],
            ['name' => 'Temuco', 'province_id' => 41],
            ['name' => 'Carahue', 'province_id' => 41],
            ['name' => 'Cunco', 'province_id' => 41],
            ['name' => 'Curarrehue', 'province_id' => 41],
            ['name' => 'Freire', 'province_id' => 41],
            ['name' => 'Galvarino', 'province_id' => 41],
            ['name' => 'Gorbea', 'province_id' => 41],
            ['name' => 'Lautaro', 'province_id' => 41],
            ['name' => 'Loncoche', 'province_id' => 41],
            ['name' => 'Melipeuco', 'province_id' => 41],
            ['name' => 'Nueva Imperial', 'province_id' => 41],
            ['name' => 'Padre Las Casas', 'province_id' => 41],
            ['name' => 'Perquenco', 'province_id' => 41],
            ['name' => 'Pitrufquén', 'province_id' => 41],
            ['name' => 'Pucón', 'province_id' => 41],
            ['name' => 'Saavedra', 'province_id' => 41],
            ['name' => 'Teodoro Schmidt', 'province_id' => 41],
            ['name' => 'Toltén', 'province_id' => 41],
            ['name' => 'Vilcún', 'province_id' => 41],
            ['name' => 'Villarrica', 'province_id' => 41],
            ['name' => 'Cholchol', 'province_id' => 41],
            ['name' => 'Angol', 'province_id' => 42],
            ['name' => 'Collipulli', 'province_id' => 42],
            ['name' => 'Curacautín', 'province_id' => 42],
            ['name' => 'Ercilla', 'province_id' => 42],
            ['name' => 'Lonquimay', 'province_id' => 42],
            ['name' => 'Los Sauces', 'province_id' => 42],
            ['name' => 'Lumaco', 'province_id' => 42],
            ['name' => 'Purén', 'province_id' => 42],
            ['name' => 'Renaico', 'province_id' => 42],
            ['name' => 'Traiguén', 'province_id' => 42],
            ['name' => 'Victoria', 'province_id' => 42],
            ['name' => 'Valdivia', 'province_id' => 43],
            ['name' => 'Corral', 'province_id' => 43],
            ['name' => 'Lanco', 'province_id' => 43],
            ['name' => 'Los Lagos', 'province_id' => 43],
            ['name' => 'Máfil', 'province_id' => 43],
            ['name' => 'Mariquina', 'province_id' => 43],
            ['name' => 'Paillaco', 'province_id' => 43],
            ['name' => 'Panguipulli', 'province_id' => 43],
            ['name' => 'La Unión', 'province_id' => 44],
            ['name' => 'Futrono', 'province_id' => 44],
            ['name' => 'Lago Ranco', 'province_id' => 44],
            ['name' => 'Río Bueno', 'province_id' => 44],
            ['name' => 'Puerto Montt', 'province_id' => 45],
            ['name' => 'Calbuco', 'province_id' => 45],
            ['name' => 'Cochamó', 'province_id' => 45],
            ['name' => 'Fresia', 'province_id' => 45],
            ['name' => 'Frutillar', 'province_id' => 45],
            ['name' => 'Los Muermos', 'province_id' => 45],
            ['name' => 'Llanquihue', 'province_id' => 45],
            ['name' => 'Maullín', 'province_id' => 45],
            ['name' => 'Puerto Varas', 'province_id' => 45],
            ['name' => 'Osorno', 'province_id' => 46],
            ['name' => 'Puerto Octay', 'province_id' => 46],
            ['name' => 'Purranque', 'province_id' => 46],
            ['name' => 'Puyehue', 'province_id' => 46],
            ['name' => 'Río Negro', 'province_id' => 46],
            ['name' => 'San Juan de la Costa', 'province_id' => 46],
            ['name' => 'San Pablo', 'province_id' => 46],
            ['name' => 'Castro', 'province_id' => 47],
            ['name' => 'Ancud', 'province_id' => 47],
            ['name' => 'Chonchi', 'province_id' => 47],
            ['name' => 'Curaco de Vélez', 'province_id' => 47],
            ['name' => 'Dalcahue', 'province_id' => 47],
            ['name' => 'Puqueldón', 'province_id' => 47],
            ['name' => 'Queilén', 'province_id' => 47],
            ['name' => 'Quellón', 'province_id' => 47],
            ['name' => 'Quemchi', 'province_id' => 47],
            ['name' => 'Quinchao', 'province_id' => 47],
            ['name' => 'Chaitén', 'province_id' => 48],
            ['name' => 'Futaleufú', 'province_id' => 48],
            ['name' => 'Hualaihué', 'province_id' => 48],
            ['name' => 'Palena', 'province_id' => 48],
            ['name' => 'Coyhaique', 'province_id' => 49],
            ['name' => 'Lago Verde', 'province_id' => 49],
            ['name' => 'Aysén', 'province_id' => 50],
            ['name' => 'Cisnes', 'province_id' => 50],
            ['name' => 'Guaitecas', 'province_id' => 50],
            ['name' => 'Cochrane', 'province_id' => 51],
            ['name' => 'O’Higgins', 'province_id' => 51],
            ['name' => 'Tortel', 'province_id' => 51],
            ['name' => 'Chile Chico', 'province_id' => 52],
            ['name' => 'Río Ibáñez', 'province_id' => 52],
            ['name' => 'Punta Arenas', 'province_id' => 53],
            ['name' => 'Laguna Blanca', 'province_id' => 53],
            ['name' => 'Río Verde', 'province_id' => 53],
            ['name' => 'San Gregorio', 'province_id' => 53],
            ['name' => 'Porvenir', 'province_id' => 54],
            ['name' => 'Primavera', 'province_id' => 54],
            ['name' => 'Timaukel', 'province_id' => 54],
            ['name' => 'Puerto Natales', 'province_id' => 55],
            ['name' => 'Torres del Paine', 'province_id' => 55],
            ['name' => 'Antártica', 'province_id' => 56],
            ['name' => 'Puerto Williams', 'province_id' => 56],
            ['name' => 'Cabo de Hornos', 'province_id' => 56],
        ]);
    }
}
